/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unifae.engsoft.poo3.gerenciadorDeTarefas.view;

import br.unifae.engsoft.poo3.gerenciadorDeTarefas.controller.TarefasController;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class CadastroView extends javax.swing.JFrame {
  private TarefasController tarefasController = null;

  public CadastroView(TarefasController tarefasController) {
    this.setSize(400, 540);
    this.setLocationRelativeTo(null);
    initComponents();
    this.tarefasController = tarefasController;
  } 

  @Override
  public void dispose() {
    super.dispose(); 
    MainView mainView = new MainView();      
    mainView.setVisible(true);
  } 
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    field_descricao = new javax.swing.JTextArea();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    field_dataCriacao = new javax.swing.JFormattedTextField();
    field_prazo = new javax.swing.JFormattedTextField();
    jLabel5 = new javax.swing.JLabel();
    field_prioridade = new javax.swing.JComboBox<>();
    jPanel2 = new javax.swing.JPanel();
    btn_cadastrar = new javax.swing.JButton();
    btn_cancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(400, 540));
    setPreferredSize(new java.awt.Dimension(400, 540));
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Cadastro de Tarefas");
    jLabel1.setToolTipText("");

    field_descricao.setColumns(20);
    field_descricao.setRows(5);
    jScrollPane1.setViewportView(field_descricao);

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel2.setText("Descrição da tarefa");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel3.setText("Data da criação");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel4.setText("Prioridade");

    try {
      field_dataCriacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    field_dataCriacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    field_dataCriacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        field_dataCriacaoActionPerformed(evt);
      }
    });

    try {
      field_prazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    field_prazo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel5.setText("Prazo (opcional)");

    field_prioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
    field_prioridade.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        field_prioridadeActionPerformed(evt);
      }
    });

    btn_cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btn_cadastrar.setText("Cadastrar");
    btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cadastrarActionPerformed(evt);
      }
    });

    btn_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btn_cancelar.setText("Cancelar");
    btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(0, 25, Short.MAX_VALUE)
        .addComponent(btn_cadastrar)
        .addGap(60, 60, 60)
        .addComponent(btn_cancelar)
        .addGap(0, 24, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_cadastrar)
          .addComponent(btn_cancelar))
        .addGap(10, 10, 10))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(field_dataCriacao, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(field_prioridade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(field_prazo, javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
            .addGap(50, 50, 50))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel1)
        .addGap(20, 20, 20)
        .addComponent(jLabel2)
        .addGap(10, 10, 10)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(10, 10, 10)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(field_prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(10, 10, 10)
        .addComponent(jLabel3)
        .addGap(10, 10, 10)
        .addComponent(field_dataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(10, 10, 10)
        .addComponent(jLabel5)
        .addGap(10, 10, 10)
        .addComponent(field_prazo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20))
    );

    jLabel1.getAccessibleContext().setAccessibleName("Cadastro");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(10, 10, 10))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(10, 10, 10))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
      String descricao = field_descricao.getText();
      int prioridade = Integer.parseInt(field_prioridade.getSelectedItem().toString());
      String dataCriacao = field_dataCriacao.getText();
      String prazo = field_prazo.getText(); 
      
      Boolean result = tarefasController.createTarefa(descricao, prioridade, dataCriacao, prazo);         
      
      if(result){
	JOptionPane.showMessageDialog(null, "Tarefa criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
	this.dispose();
      }else{
	JOptionPane.showMessageDialog(null, "Falha na criação da tarefa.", "Erro", JOptionPane.ERROR_MESSAGE);
      }     
    }//GEN-LAST:event_btn_cadastrarActionPerformed

  private void field_dataCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_dataCriacaoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_field_dataCriacaoActionPerformed

  private void field_prioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_prioridadeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_field_prioridadeActionPerformed

  private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
    this.dispose();
  }//GEN-LAST:event_btn_cancelarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_cadastrar;
  private javax.swing.JButton btn_cancelar;
  private javax.swing.JFormattedTextField field_dataCriacao;
  private javax.swing.JTextArea field_descricao;
  private javax.swing.JFormattedTextField field_prazo;
  private javax.swing.JComboBox<String> field_prioridade;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
